local:
  openAiBucket: "http://localhost:4566"
  accessKeyId: "test"
  secretAccessKey: "test"
  exportBucket: "yabble-export-bucket-customer-sandbox"
customerSanbox:
  exportBucket: "yabble-export-bucket-customer-sandbox"
dev:
  secureTest: ${ssm:secureTest~true}
  exportBucket: "yabble-exports-dev"
dmitrii:
  exportBucket: "yabble-exports-dmitrtii"
staging:
  exportBucket: "yabble-exports-staging"
production:
  #exportBucket: "backups.yabblezone.net"
  #exportBucket: "cdn.dmitrii.connection-engine.net"
  #exportBucket: "exports.staging.yabblezone.net"
  #exportBucket: "yabble-exports-production"
  exportBucket: "yabble-exports-production"
